import img1 from "./../../assets/Project images/7.png";
import img2 from "./../../assets/Project images/1.jpg";
import img3 from "./../../assets/Project images/12.png";
import img4 from "./../../assets/Project images/5.png";
import img5 from "./../../assets/Project images/3.png";
import img6 from "./../../assets/Project images/4.png";
import img7 from "./../../assets/Project images/8.png";
import img8 from "./../../assets/Project images/9.png";
import img9 from "./../../assets/Project images/10.png";
import img10 from "./../../assets/Project images/11.png";
import img11 from "./../../assets/Project images/13.png";
import img12 from "./../../assets/Project images/17.png";
import img13 from "./../../assets/Project images/2.png";
import img14 from "./../../assets/Project images/6.png";
import img15 from "./../../assets/Project images/14.png";
import img16 from "./../../assets/Project images/15.png";
// import img17 from "./../../assets/Project images/1.png";
// import img18 from "./../../assets/Project images/1.png";
// import img19 from "./../../assets/Project images/1.png";
// import img20 from "./../../assets/Project images/1.jpg";
 
const Data = [
  {
    id: 16,
    img: img16,
    link: "https://projectreact-6.netlify.app/",
    title: "Dashboard-6",
    text: "HTML",
    text2: "SASS",
    text3: "React",
    dataProject: "React",
  },
  {
    id: 13,
    img: img13,
    link: "https://projectreact-3.netlify.app/",
    title: "Project-React-3",
    text: "HTML",
    text2: "SASS",
    text3: "React",
  },
  {
    id: 10,
    img: img10,
    link: "https://projectreact-1.netlify.app/",
    title: "Project-React-1",
    text: "HTML",
    text2: "SASS",
    text3: "React",
  },
  {
    id: 15,
    img: img15,
    link: "https://projectreact-5.netlify.app/",
    title: "Project-React-5",
    text: "HTML",
    text2: "SASS",
    text3: "React",
  },
  {
    id: 14,
    img: img14,
    link: "https://projectreact-4.netlify.app/",
    title: "Project-React-4",
    text: "HTML",
    text2: "SASS",
    text3: "React",
  },
  {
    id: 11,
    img: img11,
    link: "https://projectreact-2.netlify.app/",
    title: "Project-React-2",
    text: "HTML",
    text2: "SASS",
    text3: "React",
  },
  {
    id: 1,
    img: img1,
    link: "https://aam881011.github.io/CRUD/",
    title: "Product Manager System",
    text: "HTML",
    text2: "CSS",
    text3: "JS",
  },
  {
    id: 2,
    img: img2,
    link: "https://aam881011.github.io/comming-soon/",
    title: "Comming Soon",
    text: "HTML",
    text2: "CSS",
    text3: "js",
    text4: "bootstrap",
  },
  {
    id: 3,
    img: img3,
    link: "https://aam881011.github.io/website/",
    title: "Portfolio",
    text: "HTML",
    text2: "CSS",
  },
  {
    id: 4,
    img: img4,
    link: "https://aam881011.github.io/youtuby/",
    title: "youtuby",
    text: "HTML",
    text2: "CSS",
    text3: "js",
    text4: "bootstrap",
  },
  {
    id: 5,
    img: img5,
    link: "https://aam881011.github.io/agency/",
    title: "agency",
    text: "HTML",
    text2: "CSS",
    text3: "js",
    text4: "bootstrap",
  },
  {
    id: 6,
    img: img6,
    link: "https://aam881011.github.io/mobile/",
    title: "mobile",
    text: "HTML",
    text2: "CSS",
    text3: "js",
    text4: "bootstrap",
  },
  {
    id: 7,
    img: img7,
    link: "https://aam881011.github.io/login-page-1/",
    title: "login",
    text: "HTML",
    text2: "SASS",
  },
  {
    id: 8,
    img: img8,
    link: "https://aam881011.github.io/product/",
    title: "product",
    text: "HTML",
    text2: "CSS",
    text3: "js",
    text4: "bootstrap",
  },
  {
    id: 9,
    img: img9,
    link: "https://aam881011.github.io/login-page-2/",
    title: "login",
    text: "HTML",
    text2: "CSS",
  },
  // {
  //   id: 12,
  //   img: img12,
  //   link: "https://aam881011.github.io/4/",
  //   title: "website",
  //   text: "HTML",
  //   text2: "CSS",
  // },

  // {
  //   id: 17,
  //   img: img17,
  //link: "",
  //   title: "",
  // text: "HTML",
  //   text2: "CSS",
  // text3: "",
  // text4: "",
  // text5: "",
  // text6: "",
  // text7: "",
  // },
  // {
  //   id: 18,
  //   img: img18,
  //link: "",
  //   title: "",
  // text: "HTML",
  //   text2: "CSS",
  // text3: "",
  // text4: "",
  // text5: "",
  // text6: "",
  // text7: "",
  // },
  // {
  //   id: 19,
  //   img: img19,
  //link: "",
  //   title: "",
  // text: "HTML",
  //   text2: "CSS",
  // text3: "",
  // text4: "",
  // text5: "",
  // text6: "",
  // text7: "",
  // },

  //{
  //   id: 20,
  //   img: img20,
  //link: "",
  //   title: "",
  //   text2: "CSS",
  // text3: "",
  // text4: "",
  // text5: "",
  // text6: "",
  // text7: "",
  // },
  // {
  //   id: 21,
  //   img: img,
  //link: "",
  //   title: "",
  //   text: "",
  // },
  // {
  //   id: 22,
  //   img: img,
  //link: "",
  //   title: "",
  //   text: "",
  // },
  // {
  //   id: 23,
  //   img: img,
  //link: "",
  //   title: "",
  //   text: "",
  // },
  // {
  //   id: 24,
  //   img: img,
  //link: "",
  //   title: "",
  //   text: "",
  // },
  // {
  //   id: 25,
  //   img: img,
  //link: "",
  //   title: "",
  //   text: "",
  // },
  // {
  //   id: 26,
  //   img: img,
  //link: "",
  //   title: "",
  //   text: "",
  // },
  // {
  //   id: 27,
  //   img: img,
  //link: "",
  //   title: "",
  //   text: "",
  // },
  // {
  //   id: 28,
  //   img: img,
  //link: "",
  //   title: "",
  //   text: "",
  // },
  // {
  //   id: 29,
  //   img:img ,
  //link: "",
  //   title: "",
  //   text: "",
  // },
  // {
  //   id: 30,
  //   img: img,
  //link: "",
  //   title: "",
  //   text: "",
  // },
];

export default Data;
